#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'gkeyring==0.3','console_scripts','gkeyring'
__requires__ = 'gkeyring==0.3'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('gkeyring==0.3', 'console_scripts', 'gkeyring')()
    )
