#!/bin/bash
if [ $1 == "-u" ]
then
	echo "Umount Media"
	sudo umount /media/nemo/Media
	echo "Umounting /media/nemo/live"
	sudo umount /media/nemo/live
	echo "Umounting /media/nemo/home/nemo"
	sudo umount /media/nemo/home/nemo
	echo "Unmounting /media/nemo/home"
	sudo umount /media/nemo/home
else	
	echo "Mounting /dev/sdb1 on /media via mount -a"
	sudo mount -a
	echo "Mounting /dev/sdb2 on /media/nemo/home"
	sudo mount /dev/sdb2 /media/nemo/home
	echo "Mounting /dev/sdb3 on /media/nemo/live"
	sudo mount /dev/sdb3 /media/nemo/live
	echo "Mounting encrypted partition"
	echo "Fetching passphrase from gnome-keyring"
	export PASSPHRASE=`gkeyring --name 'seagate_passphrase' -l -o secret`
	export FNEK_SIG=`gkeyring --name 'seagate_fnek_sig' -l -o secret`

	#We use the method of adding passphrase to a file because command line args can be read by ps
	echo "passphrase_passwd=$PASSPHRASE" > /tmp/passphrase
	#Add the passphrase to ecryptfs manager
	echo $PASSPHRASE | sudo ecryptfs-add-passphrase --fnek
	#Mount the encrypted partition
	sudo mount -t ecryptfs /media/nemo/home/.ecryptfs/nemo/.Private/ /media/nemo/home/nemo/ -o ecryptfs_sig=1b2d93c21180690d,ecryptfs_fnek_sig=$FNEK_SIG,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_passthrough=n,key=passphrase:passphrase_passwd_file=/tmp/passphrase
	echo "Deleting passphrase file"
	rm /tmp/passphrase
	echo "Done"
fi