#!/bin/bash
echo "Mounting Media via mount -a"
sudo mount -a 
cd ~
rsync -rv ./TV/ /media/nemo/Media/TV/ --size-only
rsync -rv ./Downloads/ /media/nemo/Media/Downloads/ --size-only
rsync -rv ./Music/ /media/nemo/Media/Music/ --size-only
rsync -rv ./Setups/ /media/nemo/Media/Setups/ --size-only
rsync -rv ./Videos/ /media/nemo/Media/Videos/ --size-only
rsync -rv ./VirtualDrives/ /media/nemo/Media/VirtualDrives/ --size-only
rsync -rv ./Movies/ /media/nemo/Media/Movies/ --size-only
