#!/bin/bash

PATH=$PATH:/home/nemo/projects/scripts/

function sync_repo() {
  if [[ -d "$1" ]]; then
    pushd $1
    git config --bool branch.master.sync true
    git config --bool branch.master.syncNewFiles true
    git-sync
    popd
  fi
}

# xpad-notes
sync_repo /home/nemo/.config/xpad yes
# passwords
sync_repo /home/nemo/.password-store

CWD1=`pwd`
# mobile-passwords
cp -r /home/nemo/.password-store/mobile-sync/*.gpg /home/nemo/projects/personal/mobile-passwords/
sync_repo /home/nemo/projects/personal/mobile-passwords

# TODO:
# scripts?: NO
# imapfilter: YES
# /etc: YES
# dotfiles: NO
