#!/bin/bash
echo "Mounting Media via mount -a"
#sudo mount -a 
cd ~
MEDIA="/run/media/nemo/Media"
rsync -rv ./TV/ "$MEDIA/TV/" --size-only --no-links
rsync -rv ./Downloads/ "$MEDIA/Downloads/" --size-only --no-links
rsync -rv ./Music/ "$MEDIA/Music/" --size-only --no-links
rsync -rv ./Setups/ "$MEDIA/Setups/" --size-only --no-links
rsync -rv ./Videos/ "$MEDIA/Videos/" --size-only --no-links
rsync -rv ./VirtualDrives/ "$MEDIA/VirtualDrives/" --size-only --no-links
rsync -rv ./Movies/ "$MEDIA/Movies/" --size-only --no-links
