#!/bin/bash
# This script sets up my X11 environtment
# Enable all kinds of scrolling
synclient HorizEdgeScroll=1 
synclient HorizTwoFingerScroll=1
synclient CircularScrolling=1
synclient PalmDetect=1
synclient VertEdgeScroll=1
synclient VertTwoFingerScroll=1
# Disables the capslock key
setxkbmap -option caps:none
# This disables the faulty mouse wheel scroll on my usb mouse
MOUSE_ID=`xinput list |grep Logitech|egrep "[0-9]{2}" -o`
if [[ $MOUSE_ID ]]; then
    echo "Logitech Mouse connected. Disabling Scroll"
    xinput set-button-map $MOUSE_ID 1 2 3  0 0
fi
